replicas: 2  # Number of replicas (nodes or workers) to run the training
resources:
  gpu: # Optional
    accelerator_count: 1  # Number of GPUs per replica
    accelerator: mi210    # Target GPU device type
  memory: 24  # Amount of memory (GB) per replica
  cpu: 8      # Number of CPU cores per replica

# secrets: # Optional
#   HF_TOKEN: <HF_TOKEN>

# config_map: # Optional
#   FOLDER_NAME: <FOLDER_NAME> 

# Optional if you want to use shared colume between workers
# shared_volume:
#   size: 100  # Shared storage volume size (GB)

# Optional: Custom Docker image (commented out by default)
# Uncomment and configure the following section if using a custom Docker image:
# image:
#   registry: <registry>
#   name: <image_name>
#   tag: <image_tag>
#   username: <your_username>
#   password: <your_password>