resources:
  gpu:
    accelerator_count: 8
    accelerator: H100 # change it to the available accelerator in your cluster
  memory: 128
  cpu: 4
replicas: 2
config_map:
  FOLDER_NAME: "test"
  EPOCHS: "5"
  BATCH_SIZE: "256"
  LEARNING_RATE: "0.01"
shared_volume:
  size: 20